import { NextResponse } from "next/server";

// Base Mini App manifest. `accountAssociation` proves domain ownership and is
// generated by signing with the account that owns the deployment domain:
//   npx create-onchain --manifest   (or the Base manifest tool)
// Fill the three fields from env after signing; the miniapp block can ship now.
const URL = process.env.NEXT_PUBLIC_URL ?? "https://stax.vercel.app";

export async function GET() {
  return NextResponse.json({
    accountAssociation: {
      header: process.env.FARCASTER_HEADER ?? "",
      payload: process.env.FARCASTER_PAYLOAD ?? "",
      signature: process.env.FARCASTER_SIGNATURE ?? "",
    },
    miniapp: {
      version: "1",
      name: "STAX",
      subtitle: "Tokenized stock baskets",
      description:
        "Build, value and track a personal basket of Coinbase tokenized stocks on Base. Save it onchain, set price alerts.",
      iconUrl: `${URL}/icon.png`,
      homeUrl: URL,
      splashImageUrl: `${URL}/splash.png`,
      splashBackgroundColor: "#0a0b0d",
      primaryCategory: "finance",
      tags: ["defi", "stocks", "base", "portfolio", "b20"],
    },
  });
}
